// 把 HSK 一级的「英文释义 + 3 条例句（中文 + 英文翻译）」合并进 public/dicts/hsk1.json。
// 仅补充 examples / example / exampleTrans / trans 字段，不改动原有拼音等字段；缺映射的词跳过。
// 运行：node scripts/enrich-hsk1.mjs  （在 web/ 目录下）
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const dictPath = join(__dirname, '..', 'public', 'dicts', 'hsk1.json')

// word -> { trans: 英文释义, ex: [[中文例句, 英文翻译], ...3] }
const DATA = {
  '我': { trans: 'I; me (first-person pronoun)', ex: [['我喜欢学习中文。', 'I like learning Chinese.'], ['我是学生。', 'I am a student.'], ['我的家在中国。', 'My home is in China.']] },
  '你': { trans: 'you (second person, singular)', ex: [['你好吗？', 'How are you?'], ['你是老师吗？', 'Are you a teacher?'], ['我喜欢和你一起学习。', 'I like studying with you.']] },
  '他': { trans: 'he; him', ex: [['他是我的朋友。', 'He is my friend.'], ['他在看书。', 'He is reading a book.'], ['他喜欢喝咖啡。', 'He likes to drink coffee.']] },
  '她': { trans: 'she; her', ex: [['她在听音乐。', 'She is listening to music.'], ['她是医生。', 'She is a doctor.'], ['她的名字叫小雨。', 'Her name is Xiaoyu.']] },
  '我们': { trans: 'we; us', ex: [['我们是同学。', 'We are classmates.'], ['我们一起去学校。', 'We go to school together.'], ['我们的老师很好。', 'Our teacher is very nice.']] },
  '你们': { trans: 'you (plural)', ex: [['你们好！', 'Hello, everyone!'], ['你们想喝什么？', 'What would you like to drink?'], ['你们来自哪里？', 'Where are you from?']] },
  '他们': { trans: 'they; them', ex: [['他们在吃饭。', 'They are eating.'], ['他们是我的朋友。', 'They are my friends.'], ['他们在公园玩。', 'They are playing in the park.']] },
  '的': { trans: "(particle) indicates possession or description; 's", ex: [['这是我的书。', 'This is my book.'], ['我的妈妈是老师。', 'My mother is a teacher.'], ['那是他的车。', 'That is his car.']] },
  '了': { trans: '(particle) indicates a completed action', ex: [['我吃了早饭。', 'I ate breakfast.'], ['他走了。', 'He left.'], ['我看了一本书。', 'I read a book.']] },
  '是': { trans: 'to be (am / is / are)', ex: [['他是老师。', 'He is a teacher.'], ['这是苹果。', 'This is an apple.'], ['北京是中国的首都。', 'Beijing is the capital of China.']] },
  '不': { trans: 'not (negation)', ex: [['我不喜欢咖啡。', "I don't like coffee."], ['他不在家。', 'He is not at home.'], ['这不是我的书。', "This is not my book."]] },
  '在': { trans: 'at; in; to be located; (an action in progress)', ex: [['我在家。', 'I am at home.'], ['他在学校。', 'He is at school.'], ['妈妈在做饭。', 'Mom is cooking.']] },
  '有': { trans: 'to have; there is / are', ex: [['我有一本书。', 'I have a book.'], ['桌子上有两个苹果。', 'There are two apples on the desk.'], ['他有哥哥。', 'He has an older brother.']] },
  '和': { trans: 'and; with', ex: [['我和朋友去公园。', 'I go to the park with my friend.'], ['咖啡和茶。', 'Coffee and tea.'], ['我和妈妈在家。', 'Mom and I are at home.']] },
  '都': { trans: 'all; both', ex: [['我们都很好。', 'We are all fine.'], ['他们都来了。', 'They all came.'], ['大家都很喜欢。', 'Everyone likes it very much.']] },
  '很': { trans: 'very', ex: [['今天很热。', 'It is very hot today.'], ['她很漂亮。', 'She is very beautiful.'], ['这个菜很好吃。', 'This dish is very delicious.']] },
  '也': { trans: 'also; too', ex: [['我也想去。', 'I want to go too.'], ['他也会中文。', 'He can also speak Chinese.'], ['我也喜欢这本书。', 'I like this book too.']] },
  '还': { trans: 'still; yet; also', ex: [['我还在工作。', 'I am still working.'], ['你还要茶吗？', 'Do you still want tea?'], ['他还没来。', 'He has not come yet.']] },
  '又': { trans: 'again', ex: [['他又迟到了。', 'He is late again.'], ['我又忘了。', 'I forgot again.'], ['他又要了一杯咖啡。', 'He ordered another cup of coffee.']] },
  '太': { trans: 'too; extremely', ex: [['太贵了！', "It's too expensive!"], ['今天太热了。', 'It is too hot today.'], ['太好了！', "That's great!"]] },
  '吧': { trans: '(particle) suggests an action; let us', ex: [['我们走吧。', "Let's go."], ['吃饭吧。', "Let's eat."], ['回家吧。', "Let's go home."]] },
  '呢': { trans: '(particle) how about...?', ex: [['你呢？', 'How about you?'], ['我很好，你呢？', "I'm fine, and you?"], ['他在哪儿呢？', 'Where is he then?']] },
  '吗': { trans: '(particle) marks a yes/no question', ex: [['你是学生吗？', 'Are you a student?'], ['他来了吗？', 'Has he come?'], ['你喜欢咖啡吗？', 'Do you like coffee?']] },
  '什么': { trans: 'what', ex: [['这是什么？', 'What is this?'], ['你喜欢什么？', 'What do you like?'], ['你在做什么？', 'What are you doing?']] },
  '谁': { trans: 'who', ex: [['谁在敲门？', 'Who is knocking at the door?'], ['他是谁？', 'Who is he?'], ['谁的书？', "Whose book is it?"]] },
  '哪': { trans: 'which', ex: [['哪个是你的？', 'Which one is yours?'], ['你要哪一个？', 'Which one do you want?'], ['哪天去？', 'Which day shall we go?']] },
  '哪儿': { trans: 'where', ex: [['你在哪儿？', 'Where are you?'], ['车站在哪儿？', 'Where is the station?'], ['你去哪儿？', 'Where are you going?']] },
  '这': { trans: 'this (near)', ex: [['这个苹果很甜。', 'This apple is very sweet.'], ['这是我的书。', 'This is my book.'], ['这是什么？', 'What is this?']] },
  '那': { trans: 'that (far)', ex: [['那个人是我哥哥。', 'That person is my older brother.'], ['那是他的车。', 'That is his car.'], ['那个公园很大。', 'That park is big.']] },
  '这儿': { trans: 'here', ex: [['请放这儿。', 'Please put it here.'], ['我就住在这儿。', 'I live right here.'], ['这儿很安静。', 'It is quiet here.']] },
  '那儿': { trans: 'there', ex: [['那儿有一家饭店。', 'There is a restaurant over there.'], ['他住在那儿。', 'He lives there.'], ['我们看那儿。', 'Let us look over there.']] },
  '多少': { trans: 'how much; how many (with a measure word)', ex: [['多少钱？', 'How much is it?'], ['你有多少钱？', 'How much money do you have?'], ['这本书多少钱？', 'How much is this book?']] },
  '几': { trans: 'how many (for small numbers)', ex: [['你有几个苹果？', 'How many apples do you have?'], ['你几岁？', 'How old are you?'], ['现在是几点？', 'What time is it?']] },
  '个': { trans: '(measure word) general, for people or objects', ex: [['我要三个苹果。', 'I want three apples.'], ['一个人。', 'One person.'], ['这个包子很好吃。', 'This baozi is delicious.']] },
  '岁': { trans: 'years old (age)', ex: [['你几岁？', 'How old are you?'], ['我二十岁。', 'I am twenty years old.'], ['他八岁了。', 'He is eight years old.']] },
  '本': { trans: '(measure word) for books', ex: [['我买了一本书。', 'I bought a book.'], ['这本词典很好。', 'This dictionary is good.'], ['三本练习册。', 'Three workbooks.']] },
  '页': { trans: 'page', ex: [['请翻到第十页。', 'Please turn to page ten.'], ['这本书有五十页。', 'This book has fifty pages.'], ['我在看第二十页。', 'I am reading page twenty.']] },
  '课': { trans: 'class; lesson', ex: [['今天的课很有意思。', "Today's class is very interesting."], ['我们上汉语课。', 'We have a Chinese class.'], ['我很喜欢这节课。', 'I like this lesson very much.']] },
  '号': { trans: 'number; date', ex: [['今天是五号。', 'Today is the fifth.'], ['我的电话号码是 1234。', 'My phone number is 1234.'], ['三号房间。', 'Room number three.']] },
  '点': { trans: "o'clock; point", ex: [['现在三点。', 'It is three o’clock now.'], ['八点了。', 'It is eight o’clock.'], ['两点见。', 'See you at two.']] },
  '分': { trans: 'minute', ex: [['现在三点十分。', 'It is ten past three.'], ['还有五分钟。', 'There are five more minutes.'], ['我等了二十分钟。', 'I waited twenty minutes.']] },
  '年': { trans: 'year', ex: [['我学习一年了。', 'I have studied for one year.'], ['今年是 2026 年。', 'This year is 2026.'], ['他来了三年。', 'He has been here for three years.']] },
  '月': { trans: 'month', ex: [['五月天气很好。', 'The weather in May is nice.'], ['今天是三月。', 'Today is March.'], ['我学了一个月。', 'I studied for one month.']] },
  '日': { trans: 'day (of the month)', ex: [['生日是十五日。', 'My birthday is on the fifteenth.'], ['一月一日是元旦。', 'January first is New Year’s Day.'], ['他每天看书。', 'He reads every day.']] },
  '星期': { trans: 'week', ex: [['星期天我不工作。', 'I don’t work on Sunday.'], ['今天是星期一。', 'Today is Monday.'], ['我每星期去一次。', 'I go once every week.']] },
  '今天': { trans: 'today', ex: [['今天天气真好。', 'The weather is really nice today.'], ['你今天忙吗？', 'Are you busy today?'], ['今天很冷。', 'It is very cold today.']] },
  '明天': { trans: 'tomorrow', ex: [['明天见。', 'See you tomorrow.'], ['明天是星期天。', 'Tomorrow is Sunday.'], ['我明天去北京。', 'I am going to Beijing tomorrow.']] },
  '昨天': { trans: 'yesterday', ex: [['昨天我去了北京。', 'I went to Beijing yesterday.'], ['昨天很热。', 'It was very hot yesterday.'], ['你昨天做什么了？', 'What did you do yesterday?']] },
  '上午': { trans: 'morning', ex: [['上午我上课。', 'I have class in the morning.'], ['上午好！', 'Good morning!'], ['我上午不在家。', 'I am not at home in the morning.']] },
  '中午': { trans: 'noon', ex: [['中午我们吃米饭。', 'We eat rice at noon.'], ['我中午休息。', 'I rest at noon.'], ['中午十二点。', 'Twelve o’clock noon.']] },
  '下午': { trans: 'afternoon', ex: [['下午我去商店。', 'I go to the shop in the afternoon.'], ['下午好！', 'Good afternoon!'], ['他下午在家。', 'He is at home in the afternoon.']] },
  '晚上': { trans: 'evening; night', ex: [['晚上我看电影。', 'I watch a movie in the evening.'], ['晚上好！', 'Good evening!'], ['我们晚上吃饭。', 'We eat in the evening.']] },
  '现在': { trans: 'now', ex: [['现在几点？', 'What time is it now?'], ['我现在在家。', 'I am at home now.'], ['现在很晚了。', 'It is late now.']] },
  '时候': { trans: 'time; moment', ex: [['吃饭的时候不要说话。', "Don't talk while eating."], ['我小的时候。', 'When I was little.'], ['下雨的时候。', 'When it rains.']] },
  '家': { trans: 'home; family', ex: [['我家有四口人。', 'There are four people in my family.'], ['我回家了。', 'I am going home.'], ['他家很大。', 'His house is big.']] },
  '学校': { trans: 'school', ex: [['学校很大。', 'The school is big.'], ['我去学校。', 'I go to school.'], ['学校里有很多学生。', 'There are many students at school.']] },
  '商店': { trans: 'shop; store', ex: [['商店里有很多东西。', 'There are many things in the shop.'], ['我去商店买水。', 'I go to the shop to buy water.'], ['这个商店很远。', 'This shop is far.']] },
  '医院': { trans: 'hospital', ex: [['他去医院了。', 'He went to the hospital.'], ['医院很大。', 'The hospital is big.'], ['我在医院工作。', 'I work at the hospital.']] },
  '车站': { trans: 'station', ex: [['车站人很多。', 'The station is very crowded.'], ['火车站在哪儿？', 'Where is the train station?'], ['我在车站等你。', 'I will wait for you at the station.']] },
  '机场': { trans: 'airport', ex: [['我去机场接朋友。', 'I go to the airport to pick up a friend.'], ['飞机场很大。', 'The airport is big.'], ['我们两点到机场。', 'We arrive at the airport at two.']] },
  '饭店': { trans: 'restaurant', ex: [['这家饭店的菜很好吃。', 'The food at this restaurant is delicious.'], ['我们去饭店吃饭。', 'We go to the restaurant to eat.'], ['饭店在马路边。', 'The restaurant is by the road.']] },
  '图书馆': { trans: 'library', ex: [['图书馆很安静。', 'The library is very quiet.'], ['我去图书馆看书。', 'I go to the library to read.'], ['图书馆在学校旁边。', 'The library is next to the school.']] },
  '办公室': { trans: 'office', ex: [['他在办公室工作。', 'He works in the office.'], ['我的办公室很小。', 'My office is small.'], ['老师在办公室。', 'The teacher is in the office.']] },
  '房间': { trans: 'room', ex: [['我的房间很小。', 'My room is small.'], ['这是我的房间。', 'This is my room.'], ['房间很干净。', 'The room is clean.']] },
  '桌子': { trans: 'desk; table', ex: [['桌子上有一本书。', 'There is a book on the desk.'], ['请擦桌子。', 'Please wipe the table.'], ['桌子很高。', 'The table is tall.']] },
  '椅子': { trans: 'chair', ex: [['请坐椅子。', 'Please sit on the chair.'], ['椅子很舒服。', 'The chair is comfortable.'], ['我有三把椅子。', 'I have three chairs.']] },
  '电脑': { trans: 'computer', ex: [['我用电脑工作。', 'I work on the computer.'], ['电脑很贵。', 'The computer is expensive.'], ['他在看电脑。', 'He is looking at the computer.']] },
  '手机': { trans: 'mobile phone; cellphone', ex: [['我的手机在哪里？', 'Where is my phone?'], ['请关手机。', 'Please turn off your phone.'], ['我用手机打电话。', 'I use my phone to call.']] },
  '书': { trans: 'book', ex: [['我爱看书。', 'I love reading books.'], ['这是我的书。', 'This is my book.'], ['我买了一本书。', 'I bought a book.']] },
  '笔': { trans: 'pen', ex: [['请给我一支笔。', 'Please give me a pen.'], ['我用笔画画。', 'I draw with a pen.'], ['这笔很好写。', 'This pen writes well.']] },
  '纸': { trans: 'paper', ex: [['我需要一张纸。', 'I need a piece of paper.'], ['请给我纸。', 'Please give me paper.'], ['纸上有一个字。', 'There is a character on the paper.']] },
  '字': { trans: 'character (written)', ex: [['这个字怎么写？', 'How do you write this character?'], ['我会写这个字。', 'I can write this character.'], ['这字很大。', 'This character is big.']] },
  '词': { trans: 'word', ex: [['这个词是什么意思？', 'What does this word mean?'], ['我会用这个词。', 'I can use this word.'], ['请写一个新词。', 'Please write a new word.']] },
  '话': { trans: 'word; speech', ex: [['他说的话我听不懂。', "I can't understand what he says."], ['请说中国话。', 'Please speak Chinese.'], ['这是好话。', 'These are kind words.']] },
  '名字': { trans: 'name', ex: [['你的名字是什么？', 'What is your name?'], ['我的名字是小明。', 'My name is Xiaoming.'], ['她叫什么名字？', 'What is her name?']] },
  '老师': { trans: 'teacher', ex: [['老师很好。', 'The teacher is very nice.'], ['他是我的老师。', 'He is my teacher.'], ['我喜欢这个老师。', 'I like this teacher.']] },
  '学生': { trans: 'student', ex: [['他是好学生。', 'He is a good student.'], ['我是学生。', 'I am a student.'], ['学校里有很多学生。', 'There are many students at school.']] },
  '医生': { trans: 'doctor', ex: [['医生帮我看病。', 'The doctor treats me.'], ['他是医生。', 'He is a doctor.'], ['我去看医生。', 'I go to see the doctor.']] },
  '工人': { trans: 'worker', ex: [['爸爸是工人。', 'My father is a worker.'], ['工人很多。', 'There are many workers.'], ['他是建筑工人。', 'He is a construction worker.']] },
  '司机': { trans: 'driver', ex: [['司机开车很快。', 'The driver drives fast.'], ['他是出租车司机。', 'He is a taxi driver.'], ['司机先生很好。', 'The driver is very nice.']] },
  '朋友': { trans: 'friend', ex: [['我有很多朋友。', 'I have many friends.'], ['他是我的朋友。', 'He is my friend.'], ['我和朋友去公园。', 'I go to the park with my friend.']] },
  '同学': { trans: 'classmate', ex: [['我的同学都很友好。', 'My classmates are all friendly.'], ['他是我的同学。', 'He is my classmate.'], ['我和同学去学校。', 'I go to school with my classmates.']] },
  '爸爸': { trans: 'father; dad', ex: [['爸爸在家里。', 'Dad is at home.'], ['我的爸爸是工人。', 'My dad is a worker.'], ['爸爸很好。', 'Dad is very nice.']] },
  '妈妈': { trans: 'mother; mom', ex: [['妈妈做晚饭。', 'Mom makes dinner.'], ['我的妈妈是老师。', 'My mom is a teacher.'], ['我爱妈妈。', 'I love Mom.']] },
  '儿子': { trans: 'son', ex: [['他的儿子上小学。', 'His son is in primary school.'], ['我有一个儿子。', 'I have a son.'], ['儿子在家。', 'The son is at home.']] },
  '女儿': { trans: 'daughter', ex: [['女儿想去公园。', 'My daughter wants to go to the park.'], ['我有一个女儿。', 'I have a daughter.'], ['女儿很可爱。', 'The daughter is very cute.']] },
  '先生': { trans: 'Mr.; sir', ex: [['张先生是公司老板。', 'Mr. Zhang is the boss of the company.'], ['先生，你好。', 'Hello, sir.'], ['这位先生是我老师。', 'This gentleman is my teacher.']] },
  '小姐': { trans: 'Miss; young lady', ex: [['服务员小姐很客气。', 'The waitress is very polite.'], ['小姐，你好。', 'Hello, miss.'], ['那位小姐是学生。', 'That young lady is a student.']] },
  '人': { trans: 'person; people', ex: [['这里没有人。', 'There is no one here.'], ['很多人。', 'Many people.'], ['他是一个人。', 'He is alone.']] },
  '男人': { trans: 'man', ex: [['那个男人是医生。', 'That man is a doctor.'], ['他是男人。', 'He is a man.'], ['两个男人。', 'Two men.']] },
  '女人': { trans: 'woman', ex: [['那个女人在看书。', 'That woman is reading a book.'], ['她是女人。', 'She is a woman.'], ['三个女人。', 'Three women.']] },
  '孩子': { trans: 'child; children', ex: [['孩子们在学校。', 'The children are at school.'], ['我爱孩子。', 'I love children.'], ['这个孩子很乖。', 'This child is well-behaved.']] },
  '大家': { trans: 'everyone', ex: [['大家好！', 'Hello everyone!'], ['大家都来了。', 'Everyone has come.'], ['大家吃饭吧。', 'Let us all eat.']] },
  '东西': { trans: 'thing; stuff', ex: [['这是什么东西？', 'What is this thing?'], ['我买了很多东西。', 'I bought many things.'], ['桌上有东西。', 'There is something on the desk.']] },
  '钱': { trans: 'money', ex: [['我没有钱了。', 'I have no money left.'], ['这个多少钱？', 'How much is this?'], ['我需要钱。', 'I need money.']] },
  '卡': { trans: 'card', ex: [['请刷银行卡。', 'Please swipe your bank card.'], ['这是我的卡。', 'This is my card.'], ['我有会员卡。', 'I have a membership card.']] },
  '票': { trans: 'ticket', ex: [['我买了一张火车票。', 'I bought a train ticket.'], ['这是电影票。', 'This is a movie ticket.'], ['请给我票。', 'Please give me the ticket.']] },
  '水': { trans: 'water', ex: [['我想喝水。', 'I want to drink water.'], ['请给我一杯水。', 'Please give me a glass of water.'], ['水里有很多鱼。', 'There are many fish in the water.']] },
  '茶': { trans: 'tea', ex: [['请给我一杯茶。', 'Please give me a cup of tea.'], ['我喜欢喝茶。', 'I like to drink tea.'], ['这是绿茶。', 'This is green tea.']] },
  '咖啡': { trans: 'coffee', ex: [['早上我喝咖啡。', 'I drink coffee in the morning.'], ['我不喜欢咖啡。', "I don't like coffee."], ['请来一杯咖啡。', 'Please bring a cup of coffee.']] },
  '牛奶': { trans: 'milk', ex: [['孩子喝牛奶。', 'The child drinks milk.'], ['我每天早上喝牛奶。', 'I drink milk every morning.'], ['请给我牛奶。', 'Please give me milk.']] },
  '水果': { trans: 'fruit', ex: [['水果对身体好。', 'Fruit is good for your health.'], ['我喜欢吃水果。', 'I like to eat fruit.'], ['商店有水果。', 'The shop has fruit.']] },
  '苹果': { trans: 'apple', ex: [['苹果很好吃。', 'Apples are delicious.'], ['我吃一个苹果。', 'I eat an apple.'], ['红苹果。', 'A red apple.']] },
  '米饭': { trans: 'rice (cooked)', ex: [['我每天吃米饭。', 'I eat rice every day.'], ['米饭很好吃。', 'The rice is delicious.'], ['请给我米饭。', 'Please give me rice.']] },
  '面条': { trans: 'noodles', ex: [['中午吃面条。', 'I eat noodles at noon.'], ['我喜欢面条。', 'I like noodles.'], ['这碗面条很好吃。', 'This bowl of noodles is delicious.']] },
  '菜': { trans: 'dish; vegetables', ex: [['妈妈做的菜很好吃。', 'The dishes Mom cooks are delicious.'], ['我喜欢这个菜。', 'I like this dish.'], ['请点菜。', 'Please order dishes.']] },
  '肉': { trans: 'meat', ex: [['我不吃肉。', 'I don’t eat meat.'], ['这个肉很好吃。', 'This meat is delicious.'], ['他买了很多肉。', 'He bought a lot of meat.']] },
  '鱼': { trans: 'fish', ex: [['鱼在水里游。', 'Fish swim in the water.'], ['我喜欢吃鱼。', 'I like to eat fish.'], ['这条鱼很大。', 'This fish is big.']] },
  '鸡蛋': { trans: 'egg', ex: [['早饭我吃鸡蛋。', 'I eat eggs for breakfast.'], ['我买了一些鸡蛋。', 'I bought some eggs.'], ['鸡蛋很好吃。', 'Eggs are delicious.']] },
  '糖': { trans: 'sugar; candy', ex: [['孩子喜欢吃糖。', 'Children like to eat candy.'], ['我不吃糖。', 'I don’t eat sugar.'], ['这糖很甜。', 'This candy is sweet.']] },
  '衣服': { trans: 'clothes', ex: [['这件衣服很漂亮。', 'This piece of clothing is very beautiful.'], ['我洗衣服。', 'I wash clothes.'], ['衣服在哪儿？', 'Where are the clothes?']] },
  '裤子': { trans: 'pants; trousers', ex: [['我的裤子脏了。', 'My pants are dirty.'], ['这条裤子很新。', 'These pants are new.'], ['我买了一条裤子。', 'I bought a pair of pants.']] },
  '鞋': { trans: 'shoes', ex: [['我的鞋在门边。', 'My shoes are by the door.'], ['这双鞋很舒服。', 'These shoes are comfortable.'], ['我穿鞋。', 'I put on shoes.']] },
  '帽子': { trans: 'hat', ex: [['冬天戴帽子。', 'Wear a hat in winter.'], ['我的帽子很好看。', 'My hat is good-looking.'], ['请戴帽子。', 'Please wear a hat.']] },
  '包': { trans: 'bag', ex: [['我的包里有书。', 'There are books in my bag.'], ['这是我的包。', 'This is my bag.'], ['我买了一个包。', 'I bought a bag.']] },
  '汽车': { trans: 'car', ex: [['他开汽车上班。', 'He drives a car to work.'], ['汽车很快。', 'Cars are fast.'], ['我喜欢这辆汽车。', 'I like this car.']] },
  '自行车': { trans: 'bicycle', ex: [['我骑自行车去学校。', 'I ride a bike to school.'], ['自行车很便宜。', 'Bicycles are cheap.'], ['他有一辆自行车。', 'He has a bicycle.']] },
  '火车': { trans: 'train', ex: [['火车很快。', 'The train is fast.'], ['我坐火车去北京。', 'I take the train to Beijing.'], ['火车站很大。', 'The train station is big.']] },
  '飞机': { trans: 'airplane', ex: [['飞机飞得很高。', 'The plane flies very high.'], ['我坐飞机去中国。', 'I fly to China.'], ['飞机很快。', 'The plane is fast.']] },
  '船': { trans: 'boat; ship', ex: [['我们坐船过河。', 'We take a boat across the river.'], ['船在水上。', 'The boat is on the water.'], ['大船。', 'A big ship.']] },
  '路': { trans: 'road; path', ex: [['这条路很长。', 'This road is very long.'], ['前面有路。', 'There is a road ahead.'], ['走路去学校。', 'Walk to school.']] },
  '桥': { trans: 'bridge', ex: [['河上有一座桥。', 'There is a bridge over the river.'], ['桥很高。', 'The bridge is high.'], ['我们过桥。', 'We cross the bridge.']] },
  '门': { trans: 'door', ex: [['请开门。', 'Please open the door.'], ['门关了。', 'The door is closed.'], ['这是我的门。', 'This is my door.']] },
  '窗': { trans: 'window', ex: [['窗开着。', 'The window is open.'], ['请关窗。', 'Please close the window.'], ['窗很大。', 'The window is big.']] },
  '猫': { trans: 'cat', ex: [['猫在睡觉。', 'The cat is sleeping.'], ['我喜欢猫。', 'I like cats.'], ['这是一只黑猫。', 'This is a black cat.']] },
  '狗': { trans: 'dog', ex: [['狗很可爱。', 'Dogs are very cute.'], ['我有狗。', 'I have a dog.'], ['狗在门外。', 'The dog is outside the door.']] },
  '鸟': { trans: 'bird', ex: [['鸟在天上飞。', 'Birds fly in the sky.'], ['我喜欢鸟。', 'I like birds.'], ['树上有鸟。', 'There is a bird in the tree.']] },
  '花': { trans: 'flower', ex: [['花园里有很多花。', 'There are many flowers in the garden.'], ['这朵花很美。', 'This flower is beautiful.'], ['我送你花。', 'I give you flowers.']] },
  '树': { trans: 'tree', ex: [['树下有椅子。', 'There is a chair under the tree.'], ['这棵树很大。', 'This tree is big.'], ['树上有鸟。', 'There is a bird in the tree.']] },
  '草': { trans: 'grass', ex: [['草地绿绿的。', 'The grass is green.'], ['羊吃草。', 'Sheep eat grass.'], ['我喜欢草。', 'I like grass.']] },
  '太阳': { trans: 'sun', ex: [['太阳出来了。', 'The sun has come out.'], ['太阳很大。', 'The sun is big.'], ['我喜欢太阳。', 'I like the sun.']] },
  '月亮': { trans: 'moon', ex: [['今晚月亮很圆。', 'The moon is full tonight.'], ['月亮很亮。', 'The moon is bright.'], ['我看月亮。', 'I look at the moon.']] },
  '天空': { trans: 'sky', ex: [['天空是蓝色的。', 'The sky is blue.'], ['鸟在天上飞。', 'Birds fly in the sky.'], ['天空很美。', 'The sky is beautiful.']] },
  '风': { trans: 'wind', ex: [['今天风很大。', 'It is very windy today.'], ['风吹树。', 'The wind blows the trees.'], ['风很冷。', 'The wind is cold.']] },
  '雨': { trans: 'rain', ex: [['下雨了。', 'It is raining.'], ['今天有雨。', 'It rains today.'], ['我不喜欢雨。', 'I don’t like rain.']] },
  '雪': { trans: 'snow', ex: [['冬天会下雪。', 'It snows in winter.'], ['雪很白。', 'The snow is white.'], ['我喜欢雪。', 'I like snow.']] },
  '山': { trans: 'mountain', ex: [['山很高。', 'The mountain is very high.'], ['我们去爬山。', 'We go mountain climbing.'], ['山上有树。', 'There are trees on the mountain.']] },
  '河': { trans: 'river', ex: [['河水很清。', 'The river water is clear.'], ['河很长。', 'The river is long.'], ['河边有花。', 'There are flowers by the river.']] },
  '海': { trans: 'sea', ex: [['海边很美。', 'The seaside is beautiful.'], ['海很大。', 'The sea is big.'], ['我喜欢海。', 'I like the sea.']] },
  '中国': { trans: 'China', ex: [['中国很大。', 'China is very big.'], ['我来自中国。', 'I am from China.'], ['中国话很好听。', 'Chinese sounds nice.']] },
  '北京': { trans: 'Beijing', ex: [['北京是中国的首都。', 'Beijing is the capital of China.'], ['我去过北京。', 'I have been to Beijing.'], ['北京很大。', 'Beijing is big.']] },
  '汉语': { trans: 'Chinese (language)', ex: [['我在学汉语。', 'I am learning Chinese.'], ['汉语很难。', 'Chinese is hard.'], ['我会说汉语。', 'I can speak Chinese.']] },
  '英语': { trans: 'English (language)', ex: [['他会说英语。', 'He can speak English.'], ['我学英语。', 'I study English.'], ['英语很好听。', 'English sounds nice.']] },
  '汉字': { trans: 'Chinese character', ex: [['汉字很难写。', 'Chinese characters are hard to write.'], ['我会写汉字。', 'I can write Chinese characters.'], ['这个汉字很大。', 'This Chinese character is big.']] },
  '拼音': { trans: 'pinyin (romanization of Chinese)', ex: [['我用拼音打字。', 'I type using pinyin.'], ['拼音很好用。', 'Pinyin is very useful.'], ['我学拼音。', 'I study pinyin.']] },
  '说': { trans: 'to speak; to say', ex: [['请再说一遍。', 'Please say it again.'], ['我会说汉语。', 'I can speak Chinese.'], ['他在说什么？', 'What is he saying?']] },
  '看': { trans: 'to look; to watch; to read', ex: [['我看黑板。', 'I look at the blackboard.'], ['我在看书。', 'I am reading a book.'], ['你看电视吗？', 'Do you watch TV?']] },
  '听': { trans: 'to listen', ex: [['我听音乐。', 'I listen to music.'], ['请听我说。', 'Please listen to me.'], ['你听见了吗？', 'Did you hear it?']] },
  '吃': { trans: 'to eat', ex: [['我吃苹果。', 'I eat an apple.'], ['你吃什么？', 'What do you eat?'], ['我们吃饭吧。', "Let's eat."]] },
  '喝': { trans: 'to drink', ex: [['我喝茶。', 'I drink tea.'], ['你想喝水吗？', 'Do you want to drink water?'], ['他喝咖啡。', 'He drinks coffee.']] },
}

const raw = JSON.parse(readFileSync(dictPath, 'utf-8'))
let filled = 0
let missing = 0
for (const w of raw.words) {
  const d = DATA[w.word]
  if (!d) {
    missing++
    console.warn('[skip] no data for:', w.word)
    continue
  }
  w.trans = d.trans
  w.examples = d.ex.map(([zh, en]) => ({ zh, en }))
  w.example = d.ex[0][0]
  w.exampleTrans = d.ex[0][1]
  filled++
}
writeFileSync(dictPath, JSON.stringify(raw), 'utf-8')
console.log(`done. filled=${filled} missing=${missing} total=${raw.words.length}`)
