export default {
  "经验": { "trans": "experience", "ex": [["他很有经验。","He is very experienced."],["我从经验中学到很多。","I learned a lot from experience."],["工作经验很重要。","Work experience is important."]] },
  "知识": { "trans": "knowledge", "ex": [["知识就是力量。","Knowledge is power."],["他有很多知识。","He has a lot of knowledge."],["我们要学习知识。","We should learn knowledge."]] },
  "能力": { "trans": "ability; capability", "ex": [["他有能力完成任务。","He has the ability to finish the task."],["学习能力很重要。","The ability to learn is important."],["她展现出很强的能力。","She showed strong ability."]] },
  "态度": { "trans": "attitude", "ex": [["他的态度很好。","His attitude is good."],["态度决定一切。","Attitude decides everything."],["请保持积极的态度。","Please keep a positive attitude."]] },
  "目标": { "trans": "goal; target", "ex": [["我的目标是学好汉语。","My goal is to learn Chinese well."],["我们达成了目标。","We achieved our goal."],["设定目标很重要。","Setting goals is important."]] },
  "计划": { "trans": "plan", "ex": [["我有学习计划。","I have a study plan."],["请按计划进行。","Please proceed according to the plan."],["这个计划很好。","This plan is good."]] },
  "方法": { "trans": "method; way", "ex": [["这是好方法。","This is a good method."],["学习方法很重要。","The method of study is important."],["请告诉我方法。","Please tell me the way."]] },
  "结果": { "trans": "result", "ex": [["结果很好。","The result is good."],["我们等结果。","We are waiting for the result."],["努力会有好结果。","Hard work brings good results."]] },
  "原因": { "trans": "reason; cause", "ex": [["原因是什么？","What is the reason?"],["他说明了原因。","He explained the reason."],["因为什么原因？","For what reason?"]] },
  "条件": { "trans": "condition", "ex": [["条件很好。","The conditions are good."],["这是必要条件。","This is a necessary condition."],["我们满足所有条件。","We meet all the conditions."]] },
  "环境": { "trans": "environment", "ex": [["环境很重要。","The environment is important."],["我们要保护环境。","We should protect the environment."],["这里环境很好。","The environment here is good."]] },
  "资源": { "trans": "resource", "ex": [["资源有限。","Resources are limited."],["我们要节约资源。","We should save resources."],["自然资源很宝贵。","Natural resources are precious."]] },
  "市场": { "trans": "market", "ex": [["市场很大。","The market is big."],["我们开拓市场。","We explore the market."],["市场价格在变化。","Market prices are changing."]] },
  "产品": { "trans": "product", "ex": [["这个产品很好。","This product is good."],["我们开发新产品。","We develop new products."],["产品质量很重要。","Product quality is important."]] },
  "服务": { "trans": "service", "ex": [["服务很好。","The service is good."],["我们需要更好的服务。","We need better service."],["他们提供服务。","They provide services."]] },
  "客户": { "trans": "customer; client", "ex": [["客户很重要。","Customers are important."],["我们服务客户。","We serve customers."],["这位客户很满意。","This customer is satisfied."]] },
  "团队": { "trans": "team", "ex": [["我们是一个团队。","We are a team."],["团队合作很重要。","Teamwork is important."],["团队很努力。","The team works hard."]] },
  "管理": { "trans": "management; to manage", "ex": [["他负责管理。","He is in charge of management."],["管理很重要。","Management is important."],["学习管理知识。","Learn management knowledge."]] },
  "领导": { "trans": "leader; to lead", "ex": [["他是领导。","He is the leader."],["领导很负责。","The leader is responsible."],["他领导团队。","He leads the team."]] },
  "沟通": { "trans": "communication; to communicate", "ex": [["沟通很重要。","Communication is important."],["我们需要沟通。","We need to communicate."],["良好的沟通。","Good communication."]] },
  "合作": { "trans": "cooperation; to cooperate", "ex": [["我们合作完成。","We cooperate to finish it."],["合作很重要。","Cooperation is important."],["他们合作愉快。","They cooperated happily."]] },
  "创新": { "trans": "innovation; to innovate", "ex": [["创新很重要。","Innovation is important."],["我们要不断创新。","We must keep innovating."],["这是个创新的想法。","This is an innovative idea."]] },
  "发展": { "trans": "development; to develop", "ex": [["经济发展很快。","The economy develops fast."],["公司发展了。","The company has developed."],["发展很重要。","Development is important."]] },
  "变化": { "trans": "change; variation", "ex": [["世界在变化。","The world is changing."],["变化很快。","Changes are rapid."],["适应变化。","Adapt to changes."]] },
  "趋势": { "trans": "trend", "ex": [["这是趋势。","This is a trend."],["趋势很明显。","The trend is clear."],["把握趋势。","Grasp the trend."]] },
  "优势": { "trans": "advantage", "ex": [["我们有优势。","We have an advantage."],["发挥优势。","Give play to advantages."],["他的优势是经验。","His advantage is experience."]] },
  "风险": { "trans": "risk", "ex": [["投资有风险。","Investment has risks."],["控制风险。","Control the risk."],["请注意风险。","Please note the risk."]] },
  "机会": { "trans": "opportunity; chance", "ex": [["这是个好机会。","This is a good opportunity."],["抓住机会。","Seize the opportunity."],["我给你机会。","I give you a chance."]] },
  "挑战": { "trans": "challenge", "ex": [["这是个挑战。","This is a challenge."],["面对挑战。","Face the challenge."],["挑战很大。","The challenge is big."]] },
  "决策": { "trans": "decision; to make a decision", "ex": [["我们需要决策。","We need to make a decision."],["他做了决策。","He made a decision."],["决策很重要。","Decision-making is important."]] },
  "执行": { "trans": "execution; to execute", "ex": [["执行计划。","Execute the plan."],["执行很重要。","Execution is important."],["他们执行任务。","They carry out the task."]] },
  "效率": { "trans": "efficiency", "ex": [["效率很高。","The efficiency is high."],["提高效率。","Improve efficiency."],["工作效率很重要。","Work efficiency is important."]] },
  "质量": { "trans": "quality", "ex": [["质量很好。","The quality is good."],["保证质量。","Ensure quality."],["质量第一。","Quality first."]] },
  "标准": { "trans": "standard", "ex": [["这是标准。","This is the standard."],["达到标准。","Meet the standard."],["提高标准。","Raise the standard."]] },
  "流程": { "trans": "process; procedure", "ex": [["流程很简单。","The process is simple."],["优化流程。","Optimize the process."],["请按流程操作。","Please follow the procedure."]] },
  "制度": { "trans": "system; institution", "ex": [["公司有制度。","The company has rules."],["遵守制度。","Obey the rules."],["完善制度。","Improve the system."]] },
  "责任": { "trans": "responsibility", "ex": [["这是我的责任。","This is my responsibility."],["承担责任。","Take responsibility."],["责任感很重要。","A sense of responsibility is important."]] },
  "权利": { "trans": "right (entitlement)", "ex": [["这是我的权利。","This is my right."],["保护权利。","Protect rights."],["公民有权利。","Citizens have rights."]] },
  "义务": { "trans": "duty; obligation", "ex": [["这是义务。","This is a duty."],["履行义务。","Fulfill the duty."],["公民有纳税义务。","Citizens have the duty to pay taxes."]] },
  "法律": { "trans": "law", "ex": [["法律很重要。","Law is important."],["遵守法律。","Obey the law."],["学习法律知识。","Learn legal knowledge."]] },
  "政策": { "trans": "policy", "ex": [["国家政策。","National policy."],["了解政策。","Understand the policy."],["政策很好。","The policy is good."]] },
  "经济": { "trans": "economy; economic", "ex": [["经济发展。","The economy develops."],["经济很重要。","The economy is important."],["研究经济。","Study the economy."]] },
  "金融": { "trans": "finance", "ex": [["金融很复杂。","Finance is complex."],["学习金融。","Study finance."],["金融行业。","The finance industry."]] },
  "教育": { "trans": "education", "ex": [["教育很重要。","Education is important."],["接受教育。","Receive education."],["教育改革。","Education reform."]] },
  "医疗": { "trans": "medical treatment; healthcare", "ex": [["医疗条件好。","Medical conditions are good."],["享受医疗。","Enjoy healthcare."],["医疗很重要。","Healthcare is important."]] },
  "健康": { "trans": "health; healthy", "ex": [["身体健康。","Good health."],["保持健康。","Stay healthy."],["健康第一。","Health first."]] },
  "安全": { "trans": "safety; security", "ex": [["注意安全。","Pay attention to safety."],["安全第一。","Safety first."],["这里很安全。","It is safe here."]] },
  "交通": { "trans": "transportation; traffic", "ex": [["交通便利。","Transportation is convenient."],["交通很堵。","Traffic is congested."],["改善交通。","Improve transportation."]] },
  "旅游": { "trans": "tourism; to travel", "ex": [["我喜欢旅游。","I like traveling."],["去旅游吧。","Let us go traveling."],["旅游业发展快。","Tourism develops fast."]] },
  "美食": { "trans": "delicious food; cuisine", "ex": [["中国美食很好吃。","Chinese food is delicious."],["我喜欢美食。","I like good food."],["这里有美食。","There is good food here."]] },
  "传统": { "trans": "tradition; traditional", "ex": [["这是传统。","This is a tradition."],["文化传统。","Cultural tradition."],["尊重传统。","Respect tradition."]] }
}
