export default {
  "中国": { "trans": "China", "ex": [["我来自中国。","I am from China."],["中国很大。","China is very big."],["他在中国工作。","He works in China."]] },
  "人民": { "trans": "people", "ex": [["中国人民很友好。","The Chinese people are friendly."],["为人民服务。","Serve the people."],["人民公园很漂亮。","People's Park is beautiful."]] },
  "时间": { "trans": "time", "ex": [["时间很宝贵。","Time is precious."],["我没有时间。","I have no time."],["请准时，时间很重要。","Please be on time; time matters."]] },
  "学习": { "trans": "to study; to learn", "ex": [["我在学习汉语。","I am studying Chinese."],["学习很重要。","Learning is important."],["他每天学习两小时。","He studies two hours every day."]] },
  "工作": { "trans": "to work; a job", "ex": [["我有一份好工作。","I have a good job."],["他工作很努力。","He works very hard."],["你工作忙吗？","Are you busy at work?"]] },
  "生活": { "trans": "life; to live", "ex": [["生活很美好。","Life is beautiful."],["他的生活很平静。","His life is peaceful."],["我们快乐地生活。","We live happily."]] },
  "今天": { "trans": "today", "ex": [["今天天气很好。","The weather is nice today."],["今天是我的生日。","Today is my birthday."],["你今天忙吗？","Are you busy today?"]] },
  "明天": { "trans": "tomorrow", "ex": [["明天见。","See you tomorrow."],["明天是星期天。","Tomorrow is Sunday."],["我明天去北京。","I am going to Beijing tomorrow."]] },
  "昨天": { "trans": "yesterday", "ex": [["昨天我去了公园。","I went to the park yesterday."],["昨天很冷。","It was cold yesterday."],["你昨天做了什么？","What did you do yesterday?"]] },
  "学校": { "trans": "school", "ex": [["学校很大。","The school is big."],["我去学校上课。","I go to school for class."],["学校里有很多学生。","There are many students at school."]] },
  "老师": { "trans": "teacher", "ex": [["老师很好。","The teacher is nice."],["他是我的老师。","He is my teacher."],["我喜欢这位老师。","I like this teacher."]] },
  "学生": { "trans": "student", "ex": [["我是学生。","I am a student."],["学生们在上课。","The students are in class."],["他是个好学生。","He is a good student."]] },
  "朋友": { "trans": "friend", "ex": [["我有很多朋友。","I have many friends."],["他是我的朋友。","He is my friend."],["我的朋友来了。","My friend is here."]] },
  "家人": { "trans": "family members", "ex": [["我和家人住在一起。","I live with my family."],["家人很爱我。","My family loves me."],["春节我和家人团聚。","I reunite with my family at Spring Festival."]] },
  "父母": { "trans": "parents", "ex": [["我的父母在北京。","My parents are in Beijing."],["父母很辛苦。","Parents work very hard."],["我爱我的父母。","I love my parents."]] },
  "孩子": { "trans": "child; children", "ex": [["孩子在上学。","The child is at school."],["她有两个孩子。","She has two children."],["孩子们喜欢玩游戏。","Children like to play games."]] },
  "城市": { "trans": "city", "ex": [["这座城市很漂亮。","This city is beautiful."],["城市里有很多车。","There are many cars in the city."],["我爱大城市。","I love big cities."]] },
  "农村": { "trans": "countryside; rural area", "ex": [["农村空气很好。","The air in the countryside is good."],["他来自农村。","He is from the countryside."],["农村很安静。","The countryside is quiet."]] },
  "天气": { "trans": "weather", "ex": [["今天天气怎么样？","How is the weather today?"],["天气很冷。","The weather is cold."],["我喜欢好天气。","I like good weather."]] },
  "春天": { "trans": "spring (season)", "ex": [["春天花开了。","Flowers bloom in spring."],["春天很暖和。","Spring is warm."],["我喜欢春天。","I like spring."]] },
  "夏天": { "trans": "summer", "ex": [["夏天很热。","Summer is hot."],["夏天我去游泳。","I go swimming in summer."],["夏天很长。","Summer is long."]] },
  "秋天": { "trans": "autumn; fall", "ex": [["秋天叶子黄了。","Leaves turn yellow in autumn."],["秋天很凉快。","Autumn is cool."],["我爱秋天的景色。","I love the autumn scenery."]] },
  "冬天": { "trans": "winter", "ex": [["冬天会下雪。","It snows in winter."],["冬天很冷。","Winter is cold."],["我喜欢冬天。","I like winter."]] },
  "太阳": { "trans": "sun", "ex": [["太阳出来了。","The sun has come out."],["太阳能发光。","The sun gives light."],["太阳很大。","The sun is bright."]] },
  "月亮": { "trans": "moon", "ex": [["今晚月亮很圆。","The moon is full tonight."],["月亮挂在天上。","The moon hangs in the sky."],["我喜欢看月亮。","I like looking at the moon."]] },
  "星星": { "trans": "stars", "ex": [["天空有很多星星。","There are many stars in the sky."],["星星在眨眼睛。","The stars are twinkling."],["我爱看星星。","I love watching the stars."]] },
  "天空": { "trans": "sky", "ex": [["天空是蓝色的。","The sky is blue."],["鸟在天上飞。","Birds fly in the sky."],["天空很美。","The sky is beautiful."]] },
  "大海": { "trans": "sea; ocean", "ex": [["大海很大。","The sea is vast."],["我喜欢大海。","I like the sea."],["海里有鱼。","There are fish in the sea."]] },
  "高山": { "trans": "high mountain", "ex": [["高山很高。","The mountain is high."],["我们爬高山。","We climb the high mountain."],["高山上有雪。","There is snow on the high mountain."]] },
  "河流": { "trans": "river", "ex": [["河水很清。","The river water is clear."],["河流很长。","The river is long."],["河边有树。","There are trees by the river."]] },
  "树木": { "trans": "trees", "ex": [["树木很多。","There are many trees."],["树木绿绿的。","The trees are green."],["我们要保护树木。","We should protect trees."]] },
  "花草": { "trans": "flowers and plants", "ex": [["花草很香。","Flowers and plants smell sweet."],["花园里有很多花草。","There are many flowers and plants in the garden."],["请勿踩踏花草。","Please do not step on the plants."]] },
  "动物": { "trans": "animal", "ex": [["动物是人类的朋友。","Animals are friends of humans."],["我喜欢小动物。","I like small animals."],["动物园有很多动物。","The zoo has many animals."]] },
  "世界": { "trans": "world", "ex": [["世界很大。","The world is big."],["我想看看世界。","I want to see the world."],["世界和平很重要。","World peace is important."]] },
  "国家": { "trans": "country", "ex": [["中国是一个国家。","China is a country."],["每个国家都有自己的文化。","Every country has its own culture."],["他访问了很多国家。","He has visited many countries."]] },
  "社会": { "trans": "society", "ex": [["社会在进步。","Society is progressing."],["我们要为社会做贡献。","We should contribute to society."],["社会很复杂。","Society is complex."]] },
  "文化": { "trans": "culture", "ex": [["中国文化很有名。","Chinese culture is famous."],["我喜欢中国文化。","I like Chinese culture."],["不同国家有不同文化。","Different countries have different cultures."]] },
  "历史": { "trans": "history", "ex": [["中国历史悠久。","China has a long history."],["我对历史很感兴趣。","I am interested in history."],["历史很重要。","History is important."]] },
  "科学": { "trans": "science", "ex": [["科学很有趣。","Science is interesting."],["他喜欢科学。","He likes science."],["科学改变生活。","Science changes life."]] },
  "技术": { "trans": "technology", "ex": [["技术发展很快。","Technology develops fast."],["新技术很好用。","The new technology is easy to use."],["我们需要技术。","We need technology."]] },
  "电脑": { "trans": "computer", "ex": [["我用电脑工作。","I work on the computer."],["电脑很方便。","Computers are convenient."],["他买了一台电脑。","He bought a computer."]] },
  "手机": { "trans": "mobile phone; cellphone", "ex": [["我的手机在哪里？","Where is my phone?"],["手机很有用。","Mobile phones are useful."],["请用手机联系我。","Please contact me by phone."]] },
  "网络": { "trans": "internet; network", "ex": [["网络很快。","The internet is fast."],["我离不开网络。","I cannot live without the internet."],["网络坏了。","The network is down."]] },
  "信息": { "trans": "information", "ex": [["我需要更多信息。","I need more information."],["这个信息很重要。","This information is important."],["请保护个人信息。","Please protect personal information."]] },
  "数据": { "trans": "data", "ex": [["这些数据很有用。","This data is useful."],["请保存数据。","Please save the data."],["数据分析很重要。","Data analysis is important."]] },
  "软件": { "trans": "software", "ex": [["这个软件很好用。","This software is easy to use."],["我下载了一个软件。","I downloaded a piece of software."],["软件需要更新。","The software needs updating."]] },
  "硬件": { "trans": "hardware", "ex": [["电脑硬件坏了。","The computer hardware is broken."],["硬件很贵。","Hardware is expensive."],["他懂硬件。","He understands hardware."]] },
  "系统": { "trans": "system", "ex": [["这个系统很好用。","This system is easy to use."],["系统出错了。","The system crashed."],["新系统上线了。","The new system is online."]] },
  "程序": { "trans": "program", "ex": [["这个程序很有用。","This program is useful."],["我在写程序。","I am writing a program."],["程序运行很快。","The program runs fast."]] },
  "语言": { "trans": "language", "ex": [["汉语是一门语言。","Chinese is a language."],["我会三种语言。","I speak three languages."],["语言很重要。","Language is important."]] },
  "文字": { "trans": "written characters; script", "ex": [["汉字是文字。","Chinese characters are a script."],["古代文字很有趣。","Ancient writing is interesting."],["他研究文字。","He studies writing systems."]] },
  "汉字": { "trans": "Chinese character", "ex": [["我会写汉字。","I can write Chinese characters."],["汉字很难。","Chinese characters are hard."],["这个汉字怎么读？","How do you pronounce this character?"]] },
  "拼音": { "trans": "pinyin (romanization)", "ex": [["我用拼音打字。","I type using pinyin."],["拼音很好学。","Pinyin is easy to learn."],["请写拼音。","Please write the pinyin."]] },
  "字母": { "trans": "letter (of alphabet)", "ex": [["英语有26个字母。","English has 26 letters."],["请写大写字母。","Please write capital letters."],["他学字母。","He is learning the alphabet."]] },
  "声音": { "trans": "sound; voice", "ex": [["声音很好听。","The voice sounds nice."],["请小声，别出声。","Please be quiet, don't make a sound."],["我听见了声音。","I heard a sound."]] },
  "音乐": { "trans": "music", "ex": [["我喜欢听音乐。","I like listening to music."],["音乐很好听。","The music is beautiful."],["他会创作音乐。","He can compose music."]] },
  "电影": { "trans": "movie; film", "ex": [["我们看电影吧。","Let us watch a movie."],["这部电影很好看。","This movie is good."],["我喜欢看电影。","I like watching movies."]] },
  "图书": { "trans": "books", "ex": [["图书馆有很多图书。","The library has many books."],["我喜欢图书。","I like books."],["请爱护图书。","Please take care of books."]] },
  "报纸": { "trans": "newspaper", "ex": [["我读报纸。","I read the newspaper."],["报纸上有新闻。","There is news in the newspaper."],["他买了一份报纸。","He bought a newspaper."]] }
}
