export default {
  "认识": { "trans": "to know (a person); be familiar with", "ex": [["我认识他。","I know him."],["你认识这位老师吗？","Do you know this teacher?"],["他认识很多汉字。","He knows many Chinese characters."]] },
  "知道": { "trans": "to know; to be aware of", "ex": [["我知道答案。","I know the answer."],["你知道吗？","Do you know?"],["他不知道这件事。","He does not know about this."]] },
  "明白": { "trans": "to understand; clear", "ex": [["我明白了。","I understand."],["请说清楚，我要明白。","Please be clear so I understand."],["这个道理很明白。","This principle is clear."]] },
  "懂": { "trans": "to understand", "ex": [["我懂中文。","I understand Chinese."],["你懂吗？","Do you understand?"],["他懂很多。","He understands a lot."]] },
  "会": { "trans": "can; to be able to (a skill)", "ex": [["我会游泳。","I can swim."],["他会说英语。","He can speak English."],["你会做饭吗？","Can you cook?"]] },
  "能": { "trans": "can; to be able to", "ex": [["我能帮你。","I can help you."],["他不能来。","He cannot come."],["你能做到。","You can do it."]] },
  "可以": { "trans": "may; can (permission)", "ex": [["我可以进来吗？","May I come in?"],["你可以走了。","You may go now."],["这里可以拍照。","You can take photos here."]] },
  "应该": { "trans": "should; ought to", "ex": [["你应该休息。","You should rest."],["我们不应该迟到。","We should not be late."],["他应该来了。","He should be here by now."]] },
  "要": { "trans": "to want; will; must", "ex": [["我要喝水。","I want to drink water."],["他要回家。","He wants to go home."],["你要加油。","You must keep going."]] },
  "想": { "trans": "to want; to think", "ex": [["我想学习。","I want to study."],["你想吃什么？","What do you want to eat?"],["我在想一个问题。","I am thinking about a question."]] },
  "喜欢": { "trans": "to like", "ex": [["我喜欢音乐。","I like music."],["他喜欢跑步。","He likes running."],["你喜欢什么颜色？","What color do you like?"]] },
  "爱": { "trans": "to love", "ex": [["我爱我的家人。","I love my family."],["他爱看书。","He loves reading."],["我们爱和平。","We love peace."]] },
  "觉得": { "trans": "to feel; to think", "ex": [["我觉得很好。","I feel good."],["你觉得呢？","What do you think?"],["他觉得很累。","He feels very tired."]] },
  "认为": { "trans": "to think; to believe", "ex": [["我认为是对的。","I think it is right."],["他认为是这样。","He believes it is so."],["大家认为很好。","Everyone thinks it is good."]] },
  "希望": { "trans": "to hope; hope", "ex": [["我希望成功。","I hope to succeed."],["希望你快乐。","I hope you are happy."],["他们希望下雨。","They hope it rains."]] },
  "打算": { "trans": "to plan; intention", "ex": [["我打算去北京。","I plan to go to Beijing."],["你打算做什么？","What do you plan to do?"],["他打算学习汉语。","He plans to study Chinese."]] },
  "决定": { "trans": "to decide; decision", "ex": [["我决定去。","I decided to go."],["他决定学习。","He decided to study."],["我们决定明天走。","We decided to leave tomorrow."]] },
  "准备": { "trans": "to prepare; ready", "ex": [["我准备考试。","I prepare for the exam."],["请准备好。","Please get ready."],["他们准备好了。","They are ready."]] },
  "开始": { "trans": "to start; beginning", "ex": [["开始上课。","Class starts."],["请开始吧。","Please begin."],["比赛开始了。","The match has started."]] },
  "结束": { "trans": "to end; finish", "ex": [["会议结束了。","The meeting ended."],["电影结束了。","The movie ended."],["工作结束了。","The work is finished."]] },
  "完成": { "trans": "to complete; to finish", "ex": [["我完成了作业。","I finished my homework."],["任务完成了。","The task is complete."],["他完成了工作。","He completed the work."]] },
  "参加": { "trans": "to participate; to join", "ex": [["我参加比赛。","I join the competition."],["他参加了会议。","He attended the meeting."],["欢迎参加。","Welcome to join."]] },
  "进来": { "trans": "to come in", "ex": [["请进来。","Please come in."],["他进来了。","He came in."],["外面冷，进来吧。","It is cold outside; come in."]] },
  "出去": { "trans": "to go out", "ex": [["我出去一下。","I will go out for a moment."],["他出去了。","He went out."],["别出去，下雨了。","Don't go out; it is raining."]] },
  "回来": { "trans": "to come back; to return", "ex": [["我回来了。","I am back."],["他还没回来。","He has not come back yet."],["你什么时候回来？","When will you come back?"]] },
  "上去": { "trans": "to go up (onto)", "ex": [["请上去吧。","Please go up."],["他上去了。","He went up."],["我们爬上去。","We climbed up."]] },
  "下来": { "trans": "to come down; down", "ex": [["请下来。","Please come down."],["他下来了。","He came down."],["雪下下来。","The snow came down."]] },
  "起床": { "trans": "to get up", "ex": [["我七点起床。","I get up at seven."],["他还没起床。","He has not gotten up yet."],["每天早早起床。","Get up early every day."]] },
  "睡觉": { "trans": "to sleep", "ex": [["我睡觉了。","I am going to sleep."],["他睡得很香。","He sleeps soundly."],["早点睡觉。","Go to sleep early."]] },
  "休息": { "trans": "to rest", "ex": [["我休息一下。","I will rest a bit."],["请休息吧。","Please rest."],["星期天我休息。","I rest on Sunday."]] },
  "洗澡": { "trans": "to take a bath/shower", "ex": [["我洗澡了。","I took a shower."],["请先洗澡。","Please take a shower first."],["他每天洗澡。","He showers every day."]] },
  "刷牙": { "trans": "to brush teeth", "ex": [["我刷牙了。","I brushed my teeth."],["请早晚刷牙。","Please brush teeth morning and night."],["孩子会刷牙。","The child can brush teeth."]] },
  "吃饭": { "trans": "to eat (a meal)", "ex": [["我们一起吃饭。","Let us eat together."],["他吃饭很快。","He eats quickly."],["请吃饭吧。","Please eat."]] },
  "上班": { "trans": "to go to work", "ex": [["我九点上班。","I go to work at nine."],["他上班去了。","He went to work."],["明天不上班。","No work tomorrow."]] },
  "下班": { "trans": "to get off work", "ex": [["我下班了。","I am off work."],["他六点下班。","He gets off at six."],["下班后去玩。","Go out after work."]] },
  "出差": { "trans": "to go on a business trip", "ex": [["我去北京出差。","I am on a business trip to Beijing."],["他出差了。","He is on a trip."],["出差一周。","A one-week business trip."]] },
  "开会": { "trans": "to have a meeting", "ex": [["我们开会。","We are having a meeting."],["他在开会。","He is in a meeting."],["明天不开会。","No meeting tomorrow."]] },
  "见面": { "trans": "to meet (in person)", "ex": [["我们见面吧。","Let us meet."],["他和朋友见面。","He met his friend."],["很高兴见面。","Nice to meet you."]] },
  "聊天": { "trans": "to chat", "ex": [["我们聊天吧。","Let us chat."],["他喜欢聊天。","He likes chatting."],["和朋友聊天很开心。","Chatting with friends is fun."]] },
  "帮忙": { "trans": "to help; to lend a hand", "ex": [["请帮忙。","Please help."],["他帮了我的忙。","He helped me."],["谢谢你的帮忙。","Thanks for your help."]] },
  "等": { "trans": "to wait", "ex": [["请等一下。","Please wait a moment."],["我等他。","I wait for him."],["等一下就好。","Just a moment."]] },
  "找": { "trans": "to look for; to find", "ex": [["我找钥匙。","I am looking for the key."],["他找工作。","He is looking for a job."],["找到了。","Found it."]] },
  "问": { "trans": "to ask", "ex": [["我问他问题。","I asked him a question."],["请随便问。","Please feel free to ask."],["他问我名字。","He asked my name."]] },
  "回答": { "trans": "to answer; reply", "ex": [["请回答我。","Please answer me."],["他回答了问题。","He answered the question."],["我知道怎么回答。","I know how to reply."]] },
  "告诉": { "trans": "to tell", "ex": [["请告诉我。","Please tell me."],["他告诉我一件事。","He told me something."],["妈妈告诉我答案。","Mom told me the answer."]] },
  "借": { "trans": "to borrow; to lend", "ex": [["我借书。","I borrow a book."],["他借给我钱。","He lent me money."],["可以借一下吗？","May I borrow it?"]] },
  "还": { "trans": "to return (something); still", "ex": [["我还书。","I return the book."],["他还给我笔。","He returned the pen to me."],["他还没来。","He has not come yet."]] },
  "买": { "trans": "to buy", "ex": [["我买苹果。","I buy apples."],["他买了车。","He bought a car."],["去超市买东西。","Go to the supermarket to buy things."]] },
  "卖": { "trans": "to sell", "ex": [["他卖房子。","He sells the house."],["这家店卖书。","This shop sells books."],["他们卖水果。","They sell fruit."]] },
  "给": { "trans": "to give", "ex": [["我给你书。","I give you the book."],["他给我钱。","He gave me money."],["请给我水。","Please give me water."]] },
  "送": { "trans": "to give; to deliver; to see off", "ex": [["我送你礼物。","I give you a gift."],["他送我回家。","He saw me home."],["快递送来了。","The delivery arrived."]] },
  "拿": { "trans": "to take; to hold", "ex": [["我拿杯子。","I take the cup."],["请拿好。","Please hold it well."],["他拿了书。","He took the book."]] },
  "放": { "trans": "to put; to place", "ex": [["请放桌上。","Please put it on the table."],["他放了书。","He placed the book."],["把包放下。","Put down the bag."]] },
  "带": { "trans": "to bring; to take along", "ex": [["请带伞。","Please bring an umbrella."],["他带朋友来。","He brought a friend."],["我带孩子去公园。","I take the child to the park."]] },
  "穿": { "trans": "to wear; to put on", "ex": [["我穿红衣服。","I wear red clothes."],["天冷，穿外套。","It is cold; wear a coat."],["他穿鞋。","He puts on shoes."]] },
  "洗": { "trans": "to wash", "ex": [["我洗衣服。","I wash clothes."],["请洗手。","Please wash your hands."],["他洗碗。","He washes dishes."]] },
  "做": { "trans": "to do; to make", "ex": [["我做饭。","I cook."],["他做作业。","He does homework."],["请做练习。","Please do the exercises."]] },
  "用": { "trans": "to use", "ex": [["我用电脑。","I use the computer."],["请用笔写。","Please write with a pen."],["这个很有用。","This is very useful."]] },
  "玩": { "trans": "to play", "ex": [["我们玩球。","We play ball."],["孩子爱玩。","Children love to play."],["去公园玩。","Go to the park to play."]] },
  "学习": { "trans": "to study; to learn", "ex": [["我学习汉语。","I study Chinese."],["学习很重要。","Learning is important."],["他每天学习。","He studies every day."]] },
  "教": { "trans": "to teach", "ex": [["我教汉语。","I teach Chinese."],["他教我开车。","He teaches me to drive."],["老师教我们。","The teacher teaches us."]] },
  "工作": { "trans": "to work; a job", "ex": [["我工作很忙。","I am busy at work."],["他工作努力。","He works hard."],["你喜欢这份工作吗？","Do you like this job?"]] },
  "努力": { "trans": "to work hard; diligent", "ex": [["我要努力学习。","I will study hard."],["他工作努力。","He works diligently."],["大家一起努力。","Everyone works hard together."]] },
  "认真": { "trans": "serious; earnest", "ex": [["请认真听讲。","Please listen carefully."],["他学习很认真。","He studies seriously."],["认真做事。","Do things earnestly."]] },
  "高兴": { "trans": "happy; glad", "ex": [["我很高兴。","I am very happy."],["他高兴地笑了。","He laughed happily."],["见到你真高兴。","Glad to see you."]] },
  "快乐": { "trans": "happy; joyful", "ex": [["祝你快乐。","Wish you happiness."],["孩子们很快乐。","The children are happy."],["快乐的生活。","A joyful life."]] },
  "生气": { "trans": "angry; to get angry", "ex": [["他生气了。","He got angry."],["别生气。","Don't be angry."],["妈妈生气了。","Mom is angry."]] },
  "难过": { "trans": "sad; upset", "ex": [["我很难过。","I am very sad."],["他很难过。","He is very sad."],["别难过。","Don't be sad."]] },
  "累": { "trans": "tired", "ex": [["我累了。","I am tired."],["工作很累。","The work is tiring."],["他累坏了。","He is exhausted."]] },
  "忙": { "trans": "busy", "ex": [["我很忙。","I am busy."],["他工作很忙。","He is busy with work."],["别太忙。","Don't be too busy."]] },
  "饿": { "trans": "hungry", "ex": [["我饿了。","I am hungry."],["你饿吗？","Are you hungry?"],["他饿坏了。","He is starving."]] },
  "渴": { "trans": "thirsty", "ex": [["我渴了。","I am thirsty."],["请给我水。","Please give me water."],["他觉得很渴。","He feels very thirsty."]] },
  "疼": { "trans": "to hurt; pain", "ex": [["我头疼。","I have a headache."],["他腿疼。","His leg hurts."],["牙疼很难受。","Toothache is awful."]] },
  "舒服": { "trans": "comfortable", "ex": [["我很舒服。","I am comfortable."],["这张床很舒服。","This bed is comfortable."],["感觉不舒服。","Feeling unwell."]] },
  "病": { "trans": "illness; to be sick", "ex": [["他病了。","He is sick."],["我生病了。","I got ill."],["注意别病了。","Be careful not to get sick."]] },
  "药": { "trans": "to take medicine", "ex": [["我吃药。","I take medicine."],["这药很苦。","The medicine is bitter."],["请按时吃药。","Please take medicine on time."]] },
  "身体": { "trans": "body; health", "ex": [["身体健康。","Good health."],["请注意身体。","Please take care of your health."],["他身体很好。","He is in good health."]] },
  "头": { "trans": "head", "ex": [["我洗头。","I wash my hair."],["他头疼。","He has a headache."],["请抬头。","Please look up."]] },
  "眼睛": { "trans": "eye", "ex": [["我的眼睛很大。","My eyes are big."],["请保护眼睛。","Please protect your eyes."],["他眼睛红了。","His eyes are red."]] },
  "耳朵": { "trans": "ear", "ex": [["我的耳朵很好。","My ears are fine."],["请大声点，我耳朵不好。","Please speak up; my ears are poor."],["他耳朵疼。","His ear hurts."]] },
  "鼻子": { "trans": "nose", "ex": [["我的鼻子很灵。","My nose is sensitive."],["他鼻子不通。","His nose is stuffed."],["请擤鼻子。","Please blow your nose."]] },
  "嘴": { "trans": "mouth", "ex": [["请闭上嘴。","Please close your mouth."],["他嘴巴甜。","He has a sweet mouth (flattering)."],["别张嘴。","Don't open your mouth."]] },
  "手": { "trans": "hand", "ex": [["我的手很巧。","My hands are skillful."],["请举手。","Please raise your hand."],["他握着我的手。","He held my hand."]] },
  "脚": { "trans": "foot; leg", "ex": [["我脚疼。","My foot hurts."],["请洗脚。","Please wash your feet."],["他用脚踢球。","He kicks the ball with his foot."]] },
  "护士": { "trans": "nurse", "ex": [["她是护士。","She is a nurse."],["护士很细心。","The nurse is careful."],["我找护士。","I am looking for the nurse."]] },
  "节日": { "trans": "festival; holiday", "ex": [["节日快乐。","Happy holiday."],["春节是重要节日。","Spring Festival is an important holiday."],["我们过节。","We celebrate the festival."]] },
  "生日": { "trans": "birthday", "ex": [["生日快乐。","Happy birthday."],["今天是我的生日。","Today is my birthday."],["他办了生日会。","He held a birthday party."]] },
  "礼物": { "trans": "gift; present", "ex": [["这是给你的礼物。","This is a gift for you."],["他送我礼物。","He gave me a gift."],["生日礼物。","A birthday gift."]] },
  "照片": { "trans": "photo; picture", "ex": [["这是我的照片。","This is my photo."],["请拍张照片。","Please take a photo."],["我们看照片。","We look at photos."]] },
  "电影": { "trans": "movie; film", "ex": [["我看电影。","I watch movies."],["这部电影好看。","This movie is good."],["我们去看电影。","Let us go to the movies."]] },
  "音乐": { "trans": "music", "ex": [["我喜欢音乐。","I like music."],["音乐很好听。","The music is nice."],["他听音乐。","He listens to music."]] },
  "电视": { "trans": "television; TV", "ex": [["我看电视。","I watch TV."],["电视坏了。","The TV is broken."],["新闻在电视上播。","News is on TV."]] },
  "报纸": { "trans": "newspaper", "ex": [["我读报纸。","I read the newspaper."],["报纸上有新闻。","There is news in the paper."],["他买报纸。","He buys a newspaper."]] },
  "消息": { "trans": "news; message", "ex": [["好消息！","Good news!"],["我收到消息。","I received a message."],["请告诉我消息。","Please tell me the news."]] },
  "天气": { "trans": "weather", "ex": [["今天天气好。","The weather is good today."],["天气冷了。","The weather is cold."],["你喜欢什么天气？","What weather do you like?"]] },
  "春天": { "trans": "spring", "ex": [["春天来了。","Spring has come."],["春天很暖和。","Spring is warm."],["我爱春天。","I love spring."]] },
  "夏天": { "trans": "summer", "ex": [["夏天很热。","Summer is hot."],["夏天游泳。","Swim in summer."],["夏天很长。","Summer is long."]] },
  "秋天": { "trans": "autumn", "ex": [["秋天凉爽。","Autumn is cool."],["秋天叶子黄。","Leaves turn yellow in autumn."],["秋天是收获季节。","Autumn is harvest season."]] },
  "冬天": { "trans": "winter", "ex": [["冬天会下雪。","It snows in winter."],["冬天很冷。","Winter is cold."],["冬天穿厚衣。","Wear thick clothes in winter."]] },
  "热": { "trans": "hot", "ex": [["天气热。","The weather is hot."],["我怕热。","I fear heat."],["水很热。","The water is hot."]] },
  "冷": { "trans": "cold", "ex": [["天气冷。","The weather is cold."],["我怕冷。","I fear the cold."],["汤冷了。","The soup is cold."]] },
  "暖和": { "trans": "warm", "ex": [["春天暖和。","Spring is warm."],["屋里很暖和。","It is warm inside."],["天气暖和了。","The weather turned warm."]] },
  "凉快": { "trans": "cool", "ex": [["秋天凉快。","Autumn is cool."],["这里很凉快。","It is cool here."],["晚上凉快。","It is cool in the evening."]] },
  "大": { "trans": "big; large", "ex": [["这个很大。","This is big."],["大城市。","A big city."],["他的声音大。","His voice is loud."]] },
  "小": { "trans": "small; little", "ex": [["这个很小。","This is small."],["小孩子。","A small child."],["小问题。","A small problem."]] },
  "多": { "trans": "many; much", "ex": [["很多书。","Many books."],["人多。","Many people."],["多少钱？","How much?"]] },
  "少": { "trans": "few; little", "ex": [["很少。","Very few."],["人少。","Few people."],["请少说话。","Please speak less."]] },
  "长": { "trans": "long", "ex": [["这条河很长。","This river is long."],["头发长。","Long hair."],["时间长。","A long time."]] },
  "短": { "trans": "short", "ex": [["时间短。","Short time."],["裤子短。","Short pants."],["头发短。","Short hair."]] },
  "高": { "trans": "tall; high", "ex": [["他很高。","He is tall."],["山高。","High mountain."],["分数高。","High score."]] },
  "矮": { "trans": "short (height)", "ex": [["他有点矮。","He is a bit short."],["矮个子。","A short person."],["这墙很矮。","This wall is low."]] },
  "新": { "trans": "new", "ex": [["新衣服。","New clothes."],["新年好。","Happy New Year."],["这是新书。","This is a new book."]] },
  "旧": { "trans": "old; used", "ex": [["旧手机。","An old phone."],["这件衣服旧了。","This clothing is worn out."],["旧房子。","An old house."]] },
  "好": { "trans": "good; well", "ex": [["很好。","Very good."],["好人。","A good person."],["天气好。","Good weather."]] },
  "坏": { "trans": "bad; broken", "ex": [["坏了。","Broken."],["坏人。","A bad person."],["天气坏。","Bad weather."]] },
  "贵": { "trans": "expensive", "ex": [["太贵了。","Too expensive."],["这个很贵。","This is expensive."],["房价贵。","Housing is pricey."]] },
  "便宜": { "trans": "cheap", "ex": [["很便宜。","Very cheap."],["这里东西便宜。","Things here are cheap."],["便宜就好。","Cheap is good."]] },
  "方便": { "trans": "convenient", "ex": [["很方便。","Very convenient."],["交通方便。","Convenient transportation."],["不方便。","Inconvenient."]] },
  "容易": { "trans": "easy", "ex": [["很容易。","Very easy."],["这个问题容易。","This problem is easy."],["学汉语不容易。","Learning Chinese is not easy."]] },
  "难": { "trans": "difficult; hard", "ex": [["很难。","Very difficult."],["这道题难。","This problem is hard."],["汉语难吗？","Is Chinese hard?"]] },
  "快": { "trans": "fast; quick", "ex": [["他跑得快。","He runs fast."],["请快一点。","Please be quicker."],["时间快到了。","Time is almost up."]] },
  "慢": { "trans": "slow", "ex": [["请慢一点。","Please slow down."],["他说话慢。","He speaks slowly."],["车开得慢。","The car drives slowly."]] },
  "早": { "trans": "early", "ex": [["我起得早。","I get up early."],["早饭。","Breakfast."],["你来早了。","You came early."]] },
  "晚": { "trans": "late", "ex": [["他来晚了。","He came late."],["晚饭。","Dinner."],["别晚了。","Don't be late."]] },
  "远": { "trans": "far", "ex": [["很远。","Very far."],["离家远。","Far from home."],["路远。","The road is long."]] },
  "近": { "trans": "near", "ex": [["很近。","Very near."],["家离学校近。","Home is near school."],["时间近了。","Time is near."]] },
  "左": { "trans": "left", "ex": [["左边。","On the left."],["向左转。","Turn left."],["我的左眼。","My left eye."]] },
  "右": { "trans": "right", "ex": [["右边。","On the right."],["向右转。","Turn right."],["他的右手。","His right hand."]] },
  "上": { "trans": "up; on; above", "ex": [["上面。","On top."],["上楼。","Go upstairs."],["桌子上。","On the table."]] },
  "下": { "trans": "down; below", "ex": [["下面。","Below."],["下楼。","Go downstairs."],["楼下。","Downstairs."]] },
  "前": { "trans": "front; before", "ex": [["前面。","In front."],["请向前走。","Please go forward."],["饭前洗手。","Wash hands before meals."]] },
  "后": { "trans": "back; after", "ex": [["后面。","Behind."],["请向后看。","Please look back."],["饭后散步。","Walk after meals."]] },
  "里": { "trans": "inside; in", "ex": [["屋里。","Inside the room."],["我心里。","In my heart."],["书里。","In the book."]] },
  "外": { "trans": "outside", "ex": [["门外。","Outside the door."],["外国。","Foreign country."],["校外。","Outside school."]] },
  "旁边": { "trans": "beside; nearby", "ex": [["桌子旁边。","Beside the table."],["他坐我旁边。","He sits next to me."],["旁边有树。","There is a tree nearby."]] },
  "中间": { "trans": "middle; between", "ex": [["中间。","In the middle."],["我们在中间。","We are in the middle."],["路中间。","In the middle of the road."]] },
  "城市": { "trans": "city", "ex": [["大城市。","A big city."],["城市生活。","City life."],["我喜欢城市。","I like cities."]] },
  "农村": { "trans": "countryside", "ex": [["农村安静。","The countryside is quiet."],["他来自农村。","He is from the countryside."],["农村空气好。","The air in the countryside is good."]] },
  "国家": { "trans": "country", "ex": [["我的国家。","My country."],["国家很大。","The country is big."],["每个国家不同。","Every country is different."]] },
  "世界": { "trans": "world", "ex": [["世界很大。","The world is big."],["全世界。","All over the world."],["世界和平。","World peace."]] },
  "时间": { "trans": "time", "ex": [["时间宝贵。","Time is precious."],["没时间。","No time."],["请准时，时间重要。","Be on time; time matters."]] },
  "地方": { "trans": "place; location", "ex": [["好地方。","A good place."],["这是哪里？","What place is this?"],["我喜欢这地方。","I like this place."]] },
  "事情": { "trans": "thing; matter", "ex": [["这件事重要。","This matter is important."],["我有事情。","I have something to do."],["别管这件事。","Don't mind this matter."]] },
  "问题": { "trans": "question; problem", "ex": [["有问题吗？","Any questions?"],["这个问题难。","This problem is hard."],["解决问题。","Solve the problem."]] },
  "答案": { "trans": "answer", "ex": [["答案正确。","The answer is correct."],["我找到答案。","I found the answer."],["请给答案。","Please give the answer."]] },
  "意思": { "trans": "meaning; idea", "ex": [["什么意思？","What does it mean?"],["这个词有意思。","This word is interesting."],["我没明白意思。","I didn't get the meaning."]] },
  "方法": { "trans": "method; way", "ex": [["好方法。","A good method."],["学习方法。","Study method."],["用这个方法。","Use this method."]] },
  "经验": { "trans": "experience", "ex": [["有经验。","Experienced."],["他的经验丰富。","He is very experienced."],["从经验学习。","Learn from experience."]] },
  "习惯": { "trans": "habit", "ex": [["好习惯。","A good habit."],["我有早起的习惯。","I have the habit of rising early."],["改掉坏习惯。","Break bad habits."]] },
  "生活": { "trans": "life; to live", "ex": [["生活很美好。","Life is beautiful."],["他的生活好。","His life is good."],["快乐地生活。","Live happily."]] }
}
