export default {
  "一心一意": { "trans": "wholeheartedly; with full attention", "ex": [["他一心一意地学习。","He studies with full attention."],["请一心一意地工作。","Please work wholeheartedly."],["她一心一意地画画。","She paints with full attention."]] },
  "三心二意": { "trans": "half-hearted; absent-minded", "ex": [["学习不能三心二意。","You cannot study half-heartedly."],["他做事三心二意。","He does things absent-mindedly."],["别三心二意了。","Stop being half-hearted."]] },
  "四面八方": { "trans": "from all sides; in all directions", "ex": [["人们从四面八方赶来。","People came from all directions."],["消息传遍四面八方。","The news spread everywhere."],["四面八方都是山。","There are mountains in all directions."]] },
  "五光十色": { "trans": "multicolored; dazzling", "ex": [["商店里五光十色。","The shop is dazzling with colors."],["灯光五光十色。","The lights are multicolored."],["节日的夜晚五光十色。","The festival night is dazzling."]] },
  "七上八下": { "trans": "anxious; unsettled (lit. seven up, eight down)", "ex": [["我的心里七上八下。","My heart is in turmoil."],["听到消息，他七上八下。","Hearing the news, he felt uneasy."],["考试前我七上八下。","I was anxious before the exam."]] },
  "九牛一毛": { "trans": "a drop in the bucket; negligible", "ex": [["这点钱只是九牛一毛。","This money is just a drop in the bucket."],["他的财富是九牛一毛。","His wealth is negligible by comparison."],["对大海来说，这点雨是九牛一毛。","To the ocean, this rain is a drop in the bucket."]] },
  "百发百中": { "trans": "every shot hits; 100% accurate", "ex": [["他百发百中。","He never misses a shot."],["神枪手百发百中。","The sharpshooter hits every time."],["他的预测百发百中。","His predictions are always accurate."]] },
  "千军万马": { "trans": "a vast army; a huge force", "ex": [["战场上有千军万马。","There is a vast army on the battlefield."],["千军万马过独木桥。","A huge crowd crosses the single-log bridge."],["他带领千军万马。","He led a huge army."]] },
  "万紫千红": { "trans": "a blaze of color; thriving", "ex": [["春天万紫千红。","Spring is a blaze of color."],["花园里万紫千红。","The garden is full of colors."],["万紫千红的春天真美。","The colorful spring is beautiful."]] },
  "自相矛盾": { "trans": "self-contradictory", "ex": [["他的话自相矛盾。","His words are self-contradictory."],["这个说法自相矛盾。","This statement contradicts itself."],["别自相矛盾。","Don't contradict yourself."]] },
  "画蛇添足": { "trans": "to ruin by adding too much; redundant", "ex": [["这真是画蛇添足。","This is really adding legs to a snake."],["多此一举，画蛇添足。","Superfluous, like adding legs to a snake."],["别画蛇添足了。","Don't gild the lily."]] },
  "守株待兔": { "trans": "wait idly for gains; foolishly hopeful", "ex": [["你不能守株待兔。","You cannot just wait idly for success."],["守株待兔是不行的。","Waiting passively does not work."],["别守株待兔了。","Don't sit around waiting."]] },
  "亡羊补牢": { "trans": "mend the fold after losing sheep; rectify in time", "ex": [["现在补救还来得及，亡羊补牢。","It is not too late to mend the fold."],["亡羊补牢，为时不晚。","Better late than never."],["出了问题要亡羊补牢。","Fix problems as soon as they appear."]] },
  "掩耳盗铃": { "trans": "deceive oneself (lit. cover ears stealing a bell)", "ex": [["这是掩耳盗铃。","This is deceiving oneself."],["别掩耳盗铃了。","Don't bury your head in the sand."],["他的做法像掩耳盗铃。","His approach is self-deception."]] },
  "刻舟求剑": { "trans": "rigid; fail to adapt", "ex": [["他这是刻舟求剑。","He is being rigid."],["情况变了，别刻舟求剑。","Things changed; don't be inflexible."],["刻舟求剑是不行的。","Being rigid does not work."]] },
  "井底之蛙": { "trans": "a frog in a well; narrow-minded", "ex": [["他像井底之蛙。","He is like a frog in a well."],["别做井底之蛙。","Don't be narrow-minded."],["井底之蛙不知大海。","A frog in a well knows not the sea."]] },
  "杯弓蛇影": { "trans": "mistaken fear; paranoid", "ex": [["他杯弓蛇影，自己吓自己。","He is paranoid, scaring himself."],["别杯弓蛇影了。","Don't be paranoid."],["这真是杯弓蛇影。","This is needless fear."]] },
  "对牛弹琴": { "trans": "cast pearls before swine; preach to deaf ears", "ex": [["对牛弹琴没用。","Playing the lute to a cow is useless."],["别对牛弹琴了。","Don't preach to deaf ears."],["跟他讲道理是对牛弹琴。","Reasoning with him is pointless."]] },
  "狐假虎威": { "trans": "bully by flaunting another's power", "ex": [["他狐假虎威。","He bullies by flaunting others' power."],["别狐假虎威。","Don't abuse borrowed authority."],["他仗势欺人，狐假虎威。","He bullies others using power."]] },
  "画龙点睛": { "trans": "add the finishing touch", "ex": [["这句话画龙点睛。","This sentence is the finishing touch."],["他的评论画龙点睛。","His comment added the perfect touch."],["最后一句画龙点睛。","The last line perfects it."]] },
  "滥竽充数": { "trans": "pass off as competent; fake it", "ex": [["他滥竽充数。","He fakes his competence."],["别滥竽充数。","Don't pretend to be skilled."],["团队里不能滥竽充数。","The team cannot have fakes."]] },
  "盲人摸象": { "trans": "take a part for the whole", "ex": [["这像盲人摸象。","This is like blind men feeling an elephant."],["别盲人摸象。","Don't judge the whole by a part."],["他的看法是盲人摸象。","His view is one-sided."]] },
  "磨杵成针": { "trans": "perseverance; grind iron to a needle", "ex": [["只要坚持，磨杵成针。","With persistence, you can grind iron to a needle."],["磨杵成针靠毅力。","Perseverance makes it possible."],["学习要磨杵成针。","Learning needs perseverance."]] },
  "破釜沉舟": { "trans": "burn one's boats; fight with no retreat", "ex": [["他破釜沉舟。","He burned his boats."],["破釜沉舟，全力以赴。","Go all out with no retreat."],["这次我们破釜沉舟。","This time we commit fully."]] },
  "塞翁失马": { "trans": "a blessing in disguise", "ex": [["塞翁失马，焉知非福。","A loss may turn out to be a gain."],["这也许是塞翁失马。","This may be a blessing in disguise."],["塞翁失马，不必难过。","Don't be sad; it may be good luck."]] },
  "熟能生巧": { "trans": "practice makes perfect", "ex": [["熟能生巧。","Practice makes perfect."],["多练，熟能生巧。","Practice more; it becomes perfect."],["打字也是熟能生巧。","Typing also improves with practice."]] },
  "望梅止渴": { "trans": "false comfort; vain hope", "ex": [["这只是望梅止渴。","This is just false comfort."],["别望梅止渴了。","Don't rely on vain hope."],["望梅止渴解决不了问题。","False comfort solves nothing."]] },
  "闻鸡起舞": { "trans": "diligent; rise at cockcrow to practice", "ex": [["他闻鸡起舞，非常勤奋。","He is diligent, rising early to practice."],["我们要闻鸡起舞。","We should be diligent."],["古人闻鸡起舞。","The ancients practiced at dawn."]] },
  "胸有成竹": { "trans": "have a well-thought-out plan", "ex": [["他胸有成竹。","He has a well-thought-out plan."],["做事要胸有成竹。","Act with a clear plan."],["她胸有成竹地回答。","She answered with confidence."]] },
  "一举两得": { "trans": "kill two birds with one stone", "ex": [["这真是一举两得。","This kills two birds with one stone."],["一举两得的好办法。","A method that gains twice."],["既能学习又能玩，一举两得。","Learn and play — two gains at once."]] },
  "精益求精": { "trans": "strive for perfection", "ex": [["他精益求精。","He strives for perfection."],["工作要精益求精。","Work should aim for excellence."],["精益求精的态度。","An attitude of constant improvement."]] },
  "锦上添花": { "trans": "add flowers to brocade; make perfect better", "ex": [["这真是锦上添花。","This adds icing to the cake."],["好上加好，锦上添花。","Better made even better."],["你的帮助是锦上添花。","Your help makes it even better."]] },
  "名副其实": { "trans": "true to its name; deserved", "ex": [["这里名副其实。","It lives up to its name."],["他是名副其实的专家。","He is a true expert."],["名副其实的美景。","A scenery true to its name."]] },
  "全力以赴": { "trans": "go all out", "ex": [["我们全力以赴。","We go all out."],["请全力以赴。","Please give it your all."],["他全力以赴地工作。","He works with all his might."]] },
  "日新月异": { "trans": "changing rapidly (each day new)", "ex": [["科技日新月异。","Technology changes daily."],["世界日新月异。","The world changes rapidly."],["城市日新月异。","The city changes fast."]] },
  "三顾茅庐": { "trans": "earnestly request; repeated visits", "ex": [["他三顾茅庐请人才。","He visited thrice to invite talent."],["三顾茅庐的精神。","The spirit of sincere invitation."],["为了项目，他三顾茅庐。","For the project, he made repeated visits."]] },
  "水到渠成": { "trans": "things fall into place when conditions are ready", "ex": [["努力后水到渠成。","With effort, success comes naturally."],["水到渠成，不必着急。","It will come in time; don't rush."],["准备充分，水到渠成。","Well prepared, it falls into place."]] },
  "无微不至": { "trans": "meticulous; with great care", "ex": [["妈妈照顾得无微不至。","Mom cares for me meticulously."],["他的关心无微不至。","His care is thorough."],["老师对我们无微不至。","The teacher cares for us deeply."]] },
  "一举成名": { "trans": "rise to fame overnight", "ex": [["他一举成名。","He rose to fame overnight."],["这位歌手一举成名。","This singer became famous at once."],["希望你能一举成名。","Hope you become famous overnight."]] },
  "坐井观天": { "trans": "limited outlook (frog in a well)", "ex": [["别坐井观天。","Don't have a limited outlook."],["坐井观天见识短。","A narrow view sees little."],["他坐井观天，不知世界大。","He has a narrow view of the world."]] }
}
